### ISSUE TITLE
tagged release

### ISSUE THREAD

**Issue by dvzrv** [luisjure/csound-vim#4]
Hi!
I'd like to package this for Arch Linux, but there is no "stable" release yet, preventing me from including this in the [community] repository.
Can you tag a release, please?

Otherwise, would it be an option to have your files as a submodule to csound, [as discussed here](https://github.com/csound/csound/issues/907#issuecomment-358017831)?

In any case: A tagged release would help me great a deal right now already!

**Comment by dvzrv** [comment]
@luisjure any update on this?
it would be great to include these...

**Comment by luisjure** [comment]
I just released the master branch as v0.7.
As it seems, it might take a while before I have time to tackle a few issues I would have liked to polish before a release.

**Comment by dvzrv** [comment]
@luisjure thanks a lot!
