### ISSUE TITLE
tags file not unique

### ISSUE THREAD

**Issue by dvzrv** [luisjure/csound-vim#5]
While trying to bake a package for vim-csound for Arch Linux, I stumbled upon the [tags](https://github.com/luisjure/csound-vim/blob/master/doc/tags) file.
Is it required to be in `$VIM/vimfiles/doc`?
I'm trying to wrap my head around this, as I think this is not a unique file in the file system (other vim plugins will also use that file). Isn't the doc folder [supposed to only contain documentation on the plugin](http://learnvimscriptthehardway.stevelosh.com/chapters/42.html#vimdoc)?
Also, what exactly does this line mean and which folder does it refer to (the [csound html documentation](https://www.archlinux.org/packages/community/x86_64/csound-doc/)?):

> After installation, run in Vim :helptags on the directory with the documentation to generate the local tags for Vim's online help system. In a system installation, the command must be run as root.

**Comment by luisjure** [comment]
Hi!

Before addressing your questions, I have to say that looking at the tags file I realized that there are many wrong entries, meaning that the Csound manual in vim-help format still has many errors. The Csound manual is real mess and parsing it to generate the vim-help file is a complete nightmare. I've been discussing this with Steven, and the next months as soon as I can liberate myself from some more pressing affairs I'll introduce the subject on the csound-dev mailing list.

As for your questions:

> Is it required to be in $VIM/vimfiles/doc?

No, in the plugin doc directory. I'm using pathogen, and that would be $HOME/.vim/bundle/csound/doc. Or whatever structure you're using for your plugins. Naturally, you'll need a configuration that allows you to have all the files of a given plugin to be under the same subdirectory.

> Also, what exactly does this line mean and which folder does it refer to (the csound html documentation?)

No, the directory with the plugin documentation (which includes an abridged version of the manual in vim-help format). To be clear, the tags file is already there, meaning that you don't actually need to run :helptags. Also, many tags are duplicated with keywords from other help files.

**Comment by dvzrv** [comment]
Okay, maybe my initial writing was a little misleading:
As this will be a system-wide package, I think that the tags file can not be shipped, because it will be used by other plugins, that are installed system-wide, too.

I'm not building a package, that is used with a vim plugin manager, but is installed into the system directories of vim (i.e. `/usr/share/vim/vimfiles/`). There, files have to be unique, which is usually the case, because file names differ as they correlate with the different plugin names (e.g. `csound.vim`).

So, `$VIM/vimfiles/doc` refers to the system-wide vim doc directory (accessible by all users, but only writable by root). btw: The folder structure below `/usr/share/vim/vimfiles/` reflects that which is used by any vim plugin (in theory).

If the location of the tags file is indeed supposed to be in the doc directory, I can not ship it, because it can not be owned by several packages at the same time.
However, users using the csound plugin can run the `:helptags` command to generate tags locally, right?

**Comment by luisjure** [comment]
el 2018-03-11 a las 06:50 David Runge escribió:

> Okay, maybe my initial writing was a little misleading:
> As this will be a system-wide package, I think that the tags file can
> not be shipped, because it will be used by other plugins, that are
> installed system-wide, too.

hi, david, sorry for the late response.

at least in local installations using a pathogen-compatible format, all the
files related to a plugin are in their own sub-directory, and not directly
under vimfiles (what  Steve Losh calls "Plugin Layout in the Dark Ages").

this allows for having different tag files for different plugins, as is
actually the case with many (most?) plugins now (the problem here is when
one tag is used by different plugins).

does the system-wide installation allow this, or is it something
pathogen-specific? i've been using pathogen for some time now to manage my
plugins, and i'm not very interested in installing plugins system-wide
with a package manager, so i don't know very well how that works. sorry i
can't be of much help...

best,

lj



-- 
luis jure
eMe - estudio de música electroacústica
http://www.eumus.edu.uy/eme/
http://www.eumus.edu.uy/docentes/jure/

**Comment by enthudave** [comment]
the tags file should simply not be in there, in the repo that is...

**Comment by enthudave** [comment]
It is the responsibility of the user to generate the tags file.
A user may use a plugin manager that does this automatically (such as Vim-Plug) or use one that doesn't (Pathogen), in which case the user could do it manually, Pathogen for example has a convenience command for this. 
Please check Pathogen's README, it talks about this.
Also read this
https://medium.com/usevim/vim-101-help-tags-d240ae415018
